version: "3.9"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    command: go run ./cmd/api -b 0.0.0.0
  
  postgres:
    image: "postgres:14.5"
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTRES_DB: ${PG_DB}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/initialize.sql:/docker-entrypoint-initdb.d/create_tables.sql